### PR TITLE
MM-841 : Remove old commons-lang lib from Gytheio

### PR DESCRIPTION
**Pull request by DenisGabriela**
- upgrade gytheio
   - remove commons-lang

### CODE REVIEW

**Comment by DenisGabriela** [comment]
`All AMPs tests` Travis job keeps failing -> https://travis-ci.com/Alfresco/acs-packaging/builds/144515406. Another AMP(s) may still need the commons-lang 2.6 lib.

**Comment by montgolfiere** [comment]
Anyway to find out via Travis which AMP (or AMPs). 

Otherwise, I guess we need to either run & repeat locally or scan the source code of all AMPs in the "all-amps" test list ?

https://github.com/Alfresco/acs-packaging/blob/master/docker-alfresco/test/docker-alfresco-all-amps-test/pom.xml

**Comment by montgolfiere** [comment]
Anyway to find out via Travis which AMP (or AMPs). 

Otherwise, I guess we need to either run & repeat locally or scan the source code of all AMPs in the "all-amps" test list ?

https://github.com/Alfresco/acs-packaging/blob/master/docker-alfresco/test/docker-alfresco-all-amps-test/pom.xml

**Comment by DenisGabriela** [comment]
Running the same commands as in the travis build I was able to find which module needs commons-lang:
`
mvn install -q -PenterpriseDocker
mvn install -q -f tests/tas-all-amps/pom.xml -DskipTests -Pall-tas-tests,prepare-wars-with-amps
docker-compose -f docker-compose-all-amps-test.yml up
`

Alfresco can't start because of the error below: 
 `Error creating bean with name 'FilePlanService_security' defined in class path resource [alfresco/module/org_alfresco_module_rm/rm-service-context.xml]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils`

Looks like RM uses the old commons-lang
I'll update my PR on acs-packaging to only update Gytheio's version and open a jira issue on RM.

**Comment by montgolfiere** [comment]
Great, thanks.

**Pull request merged**
