### PR TITLE
MM - comment-out

### PR DESCRIPTION
**Pull request by montgolfiere**
- already commented-out in [pom.xml ](https://github.com/Alfresco/acs-packaging/blame/master/pom.xml#L254-L267 )deps (REPO-5203)
- also do same for version property and remove from VERSIONS.md list

### CODE REVIEW

**Comment by montgolfiere** [comment]
Green build. Ok to merge ? cc @pieCit87 @alandavis @skopf

**Review by skopf — APPROVED** [review]
Looks good

**Review by pieCit87 — APPROVED** [review]
LGTM. 
That's one small step for a man, one giant leap for mankind.

**Comment by alandavis** [comment]
Closing as code sections to do with MM were removed

**Pull request closed without merging**
