### PR TITLE
GOOGLEDOCS-437 : Generate Final Build for GoogleDocs 3.1.0 compatible with ACS Ent 6.0

### PR DESCRIPTION
**Pull request by DenisGabriela**
- updated google-docs version

### CODE REVIEW

**Comment by DenisGabriela** [comment]
@andrei-rebegea , @aforascu , @derekhulley , @montgolfiere , please review this pull request (mentioned all of you in the comment since I don't have rights to add you as reviewers/assignees).

Thanks!

**Comment by derekhulley** [comment]
Please double-check that the same is done for the Community versions.

**Comment by derekhulley** [comment]
Since this branch was not named in the standard way, there appears to be no green build available.
We should have a green build before merging.

**Comment by DenisGabriela** [comment]
Closing this pull request (from forked project). New one open [here](https://github.com/Alfresco/acs-packaging/pull/24)

**Pull request closed without merging**
