### PR TITLE
Make dev docker-compose file work on Linux.

### PR DESCRIPTION
**Pull request by tpage-alfresco**
There is no host.docker.internal on Linux.

### CODE REVIEW

**Review by montgolfiere — APPROVED** [review]
FYI: I've not tested (I'm on  Mac - not Linux or Windows / WSL2).

**Comment by tpage-alfresco** [comment]
@montgolfiere Thanks. I checked with Alan, and this works on Mac. Unfortunately it's broken on Windows.  When I get time then I want to try something using `uname` to do different things on different OSs.

**Comment by jottley** [comment]
@tpage-alfresco is this PR still needed?

**Comment by tpage-alfresco** [comment]
No - I'll close it.

**Pull request closed without merging**
