### PR TITLE
ATS-546: Deployment updates for ATS & Misc T-Engine

### PR DESCRIPTION
**Pull request by CezarLeahu**

### CODE REVIEW

**Comment by montgolfiere** [comment]
I guess this missed the 6.2.0-RC1 tag. Is this still required ?

**Comment by CezarLeahu** [comment]
@montgolfiere Yes. But there's no branch build on Bamboo for this branch.

**Comment by montgolfiere** [comment]
OK. I've manually configured a branch build (not sure why it didn't get picked up automatically) -> PLAT-ACS564

**Comment by CezarLeahu** [comment]
Green build on the branch. I'll merge the PR.

**Pull request merged**
