### PR TITLE
 REPO-4927 : Remove Kofax module from ACS Packaging all-amps test (for 6.x)

### PR DESCRIPTION
**Pull request by elizastan**
- remove Kofax references for master

### CODE REVIEW

**Comment by cristianturlica** [comment]
Changes look good.

**Comment by montgolfiere** [comment]
Any reason not to merge ?

**Comment by elizastan** [comment]
The ACS Packaging build fails on bamboo, since bamboo is using the archived TAS project.
For ACS Packaging the bamboo build is used to do the releases, so I cannot  merge this pull request, momentarily

**Comment by elizastan** [comment]
@montgolfiere please see my comment above

**Comment by ancutam** [comment]
The builds for master and 6.2.N are fully running on Travis, and TAS tests are part of acs-packaging for these versions.
So this can be merged to **master** and **6.2.N**.

**Pull request merged**
