### PR TITLE
ATS-355 : AI-CE: Internal Release 0.4 (with zip delta distribution)

### PR DESCRIPTION
**Pull request by DenisGabriela**
- update ai-repo amp version

### CODE REVIEW

**Comment by DenisGabriela** [comment]
Wait for green build: https://bamboo.alfresco.com/bamboo/browse/PLAT-ACS301.

**Comment by montgolfiere** [comment]
@CezarLeahu @DenisGabriela LGTM - any reason not to merge ?

**Comment by DenisGabriela** [comment]
> Should we also add a line to VERSIONS.md ... ?
> 
> https://github.com/Alfresco/acs-packaging/blob/master/distribution/src/main/resources/VERSIONS.md

That line would be *Alfresco AI* or *Alfresco Intelligence Services*?

**Comment by montgolfiere** [comment]
Unless @anxumalo or @pnirwal say otherwise, I suggest "Alfresco Intelligence Services"

**Pull request merged**
