### PR TITLE
repo-4503:  upgrade hazelcast 3.11.2 on 6.1.N

### PR DESCRIPTION
**Pull request by Epurashu**

### CODE REVIEW

**Comment by Epurashu** [comment]
Exclude from acs-packaging-all-amps MM and SAML module as they are not compatible with hazelcast 3.11.2 until MM-785 and REPO-4233 are fixed.

**Comment by montgolfiere** [comment]
Note: MM-785 is targeted for ACS *6.2.0* not 6.1.x (cc @DavidRobinson8 @pnirwal). We have no current plans (or backlog items) to update and release modules for service packs.

We should take care not to introduce known breaking changes in (6.1.x) service packs. It's not just about our own modules but also likely to impact customers/partners ?

Can we revert this change and target 6.2 as originally planned ?

**Comment by Epurashu** [comment]
This is a known security vulnerability identified by our whitesource scan an also raised as an MNT issue by a customer -> https://issues.alfresco.com/jira/browse/MNT-20747
I think our alfresco external security policy enforces us to fix this on 6.0.N and 6.1.N -> https://docs.alfresco.com/support/concepts/su-external-security-policy.html

**Comment by ancutam** [comment]
Hi @montgolfiere! The Hazelcast upgrade will be reverted in the 6.1. line.

**Pull request merged**
