### PR TITLE
ATS-649: Update T-Engines version from 2.1.0 to 2.1.1

### PR DESCRIPTION
**Pull request by CezarLeahu**

### CODE REVIEW

**Comment by montgolfiere** [comment]
Anymore reviews or good to merge ? FYI: we also plan to cherry-pick back to 6.2.N.

**Comment by montgolfiere** [comment]
cc @ancutam @aforascu - we plan to merge today. Please let us know if we need to hold-off.

**Comment by tzclucian** [comment]
Kind reminder.

**Comment by aforascu** [comment]
You can continue with the merge & cherry-pick

**Pull request merged**
